DIRECTORY:
  dataset: /home/alpaco/KoDF/tall_face/onepoint/train
  #{DATA_DIR}/train

TRAINER :
  model: effnet 
  optimizer: adam
  learning_rate: 5.0e-4
  loss: bce
  metric:
    - accuracy
    - f1macro
    - confusion_matrix
  n_epochs: 5 #20
  early_stopping_target: val_accuracy
  early_stopping_patience: 5 #10
  early_stopping_mode: max
  amp: False
  gpu: 0
  seed: 42

MODEL:
  effnet:
    backbone: efficientnet_b0
    n_out: 1
    is_sigmoid: True

DATASET:
  val_size : 0.1

DATALOADER:
  batch_size: 2 #32
  num_workers: 1
  shuffle: True
  pin_memory: True
  drop_last: True

LOGGER:
  debug : False
  wandb: False
  logging_interval: 100
  plot:
    - loss
    - accuracy
    - f1macro
    - confusion_matrix
    - elapsed_time

